### ISSUE TITLE
Scrape all data for a certain period

### ISSUE THREAD

**Issue by bariscope** [ahy3nz/fastpayges#13]
Hi, this is useful script. However, Redfin only allows 10,000 downloads each time. Is there a way to modify the script to download all sales data for the entire US for last month, for example?

**Comment by bariscope** [comment]
@ahy3nz if you can have a look at my question above, that will be great :)

**Comment by ahy3nz** [comment]
Good question, I'm not sure how to configure that within the request. I would advise testing around for various possible parameters
